### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by anassCoding** [Pythalex/projet-blockchain-M2#3]
- [x] Ajouter Identifiants aux wallets.
- [x] Implementation d'envoi de transactions (Wallet A : A -> B : 100)
- [x] Miner des blocs de transactions en pow ( les transactions entrantes  sont rajoutées dans le bloc en cours et broadcast)
- [ ] Implémenter arbre de Merkle
- [ ] Un wallet peut vérifier que sa transaction est acceptée ex : 
miner -> true ( list des hash) 
miner -> false (pas reçu) ;
miner -> false (en attente prochain block)

**Comment by Pythalex** [comment]
Wallet : Transaction
Les wallets ne peuvent que envoyer de l'argent (pas en demander)

Wallet A envoie à Miner M (Transaction : (A, B, X) avec X le montant)
Miner M broadcast aux autres mineurs (A, B, X)
On peut faire en sorte que Miner M vérifie que la transaction demandée par Wallet A commence bien par "A".

**Comment by Pythalex** [comment]
Miner : 
Greetings IP PORT
NetworkNewNode IP PORT
NetworkMap NodeSet

Wallet:
Transaction Transaction = { source : string; destination : string; montant : float }   ->  faire une transaction
ShowPeers unit   ->  demander network map
Confirmation Transaction   ->  demander si la transaction a été mise dans un block miné

**Comment by Pythalex** [comment]
TODO:

- [ ] Détecter les désynchros de chains (arrivent quand deux mineurs trouvent en même 
- [ ] Envoyer toute la blockchain lors d'une désynchro
- [ ] Miner différemment entre les mineurs (pour l'instant ils partent tous de 0 donc souvent ils trouvent en même temps
- [ ] Faire des check de la blockchain lorsqu'on reçoit un bloc, pas accepter n'importe quoi
